### ISSUE TITLE
Invoke-AlerterNotification fails when input string includes an apostrophe

### ISSUE THREAD

**Issue by Windos** [markwragg/PowerShell-MacNotify#3]
Hey there @markwragg,

Had a ping from @potatoqualitee via PoshNotify today, with the following:

```powershell
Send-OSNotification -Title 'Script Completed' -Body "Sup, here's a chat" -Icon /Users/Test/Documents/twitchicon.png
```

```output
Invoke-Expression: /Users/ctrlb/.local/share/powershell/Modules/MacNotify/1.1.27/Private/Invoke-Alerter.ps1:17
Line |
  17 |              Invoke-Expression "$CommandPath $Command"
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The string is missing the terminator: '.
```

This works if you omit the Icon but fails if you include it. Tracing it through it looks like it's because the no icon variant ends up being sent to `Invoke-MacNotification` which has escaped double quotes around the text.

When you include an icon though, it goes to `Invoke-AlerterNotification` which just puts raw single quotes around the text. Pretty sure this ends up meaning that when the final command is invoked it looks little something like:

```
<snip> -subtitle 'Sup, here's a chat' <snip>
```

And the single quote in the middle of the string is causing havok.

My assumption would be that re-using the escaped double quote method from the other function would fix this, but without a Mac to test on I can't be sure.

**Comment by markwragg** [comment]
I know this was over 3 years ago, but I finally fixed it :). Should handle use of single or double quotes in the message or titles now. Use version 1.1.30 or newer for the fix. Also I made some changes to get this working again under MacOS 14, as (for me at least) it didn't seem to want to load the class any more, and I also updated to a new version of the alerter binary.
