### ISSUE TITLE
Update to macOS-latest

### ISSUE THREAD

**Issue by markwragg** [markwragg/PowerShell-MacNotify#4]
https://github.com/markwragg/PowerShell-MacNotify/blob/5f8d9c7663214f2a87e141239bdf4ba1fee3cbfd/azure-pipelines.yml#L7

**Comment by markwragg** [comment]
Build is failing using macOS-latest due to a problem installing PSDepend.

**Comment by mattpackwood** [comment]
is this still active?

**Comment by markwragg** [comment]
Do you mean the project, or this issue specifically?

**Comment by mattpackwood** [comment]
Sorry, I was not being clear, I meant the project.

**Comment by markwragg** [comment]
I haven't maintained it for a while, so I'm not sure if it still works on the latest version of MacOS. I'll give it a try at some point. You might also want to look at PoshNotify https://github.com/Windos/PoshNotify which is a cross-platform module for the same functionality, although it looks like it also hasn't been updated for a while.

**Comment by markwragg** [comment]
I fixed the build issue by removing the need to use PSDeploy which was not working under MacOS builds due to an issue with .NET YAML.

I then have made fixes to the module to get it working again under MacOS 14. I don't know if its compatible with older versions of MacOS now and am not able to test, but if you install the latest version from the gallery [1.1.29](https://www.powershellgallery.com/packages/MacNotify/1.1.29) it should now be working again.
