### ISSUE TITLE
Functions in Private folder are accessible

### ISSUE THREAD

**Issue by ElianFabian** [markwragg/PowerShell-MacNotify#5]
The functions Invoke-Alerter and Invoke-AppleScript are accessible when importing the Module.

I think the problem might be the missing Export-ModuleMember function at the end of the MacNotify.psm1 file specifying only the functions in the Public folder.

**Comment by markwragg** [comment]
Thanks for raising this, you're absolutely right its because of not using `Export-ModuleMember`. It looks like i've left it out of a few of my modules so I'll have to go around and fix, but i'll start with this one.

**Comment by markwragg** [comment]
Fixed here: https://github.com/markwragg/PowerShell-MacNotify/commit/a45ad7820899021bd1f2894d14dba3334bfb335d

A build should be running now to push a new version into the PSGallery.

**Comment by markwragg** [comment]
Should be fixed in this version: https://www.powershellgallery.com/packages/MacNotify/1.1.31
